# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: root
#   password:
#   socket: /tmp/mysql.sock

# development:
#   <<: *default
#   database: furima_38931_development

# test:
#   <<: *default
#   database: furima_38931_test

# production:
#   <<: *default
#   database: furima_38931_production
#   username: furima_38931
#   password: <%= ENV['FURIMA_38931_DATABASE_PASSWORD'] %>

# production:
#   <<: *default
#   adapter: postgresql
#   url: <%= ENV['DATABASE_URL'] %>


default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_38931_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_38931_test

production:
  <<: *default
  adapter: mysql2
  database: furima-38931_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
